M48
; DRILL file {KiCad 9.0.7} date 2026-03-25T19:51:51+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-25T19:51:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X140.7Y-18.7
X145.5Y-18.7
T2
X17.5Y-17.0
X17.5Y-72.5
X184.0Y-17.0
X184.0Y-72.0
M30
